name: Create task on issue and pull request created

on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened ]
jobs:
  addIssueAndPullRequestToProjectBoard:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-organization-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues'
      env:
        GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/creativecommons/projects/10
        GITHUB_PROJECT_COLUMN_NAME: Pending Review
    - name: add-new-pull-request-to-organization-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request'
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/creativecommons/projects/7
        GITHUB_PROJECT_COLUMN_NAME: In Progress
